---
apiVersion: v1
kind: Namespace
metadata:
  name: fluentbit-ns
  # labels:
  #   istio-injection: enabled
--- 
apiVersion: v1
kind: Service
metadata:
  name: fluentbit-svc
  namespace: fluentbit-ns
spec:
  selector:
    app: fluentbit
  ports:
  - name: http-port
    protocol: TCP
    port: 8888
    targetPort: 8888
--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit 
  namespace: fluentbit-ns
---
apiVersion: v1
kind: Pod
metadata:
  namespace: fluentbit-ns
  labels:
    app: fluentbit
  name: fluentbit
spec:
  serviceAccountName: fluentbit
  containers:
  - image: fluent/fluent-bit
    name: fluentbit
    # command: ["fluent-bit"]
    args: ["-i", "http", "-p", "port=8888", "-o", "stdout"]
    ports:
    - containerPort: 8888

