apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: trace-filter
  labels:
    # app: httpbin
  namespace: httpbin-ns
spec:
  configPatches:
    # - applyTo: HTTP_FILTER
    #   match:
    #     context: SIDECAR_OUTBOUND
    #     listener:
    #       filterChain:
    #         filter:
    #           name: envoy.filters.network.http_connection_manager
    #           subFilter:
    #             name: envoy.filters.http.router
    #   patch:
    #     operation: INSERT_BEFORE
    #     value:
    #       name: envoy.filters.http.wasm
    #       typed_config:
    #         "@type": type.googleapis.com/udpa.type.v1.TypedStruct
    #         type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
    #         value:
    #           config:
    #             name: trace-outbound-filter
    #             root_id: trace-outbound-filter
    #             # configuration:
    #             #   "@type": "type.googleapis.com/google.protobuf.StringValue"
    #             #   value: |
    #             #     {{PLUGIN_CONFIG}}
    #             vm_config:
    #               code:
    #                 local:
    #                   filename: "./api_wasm.wasm"
    #               runtime: "envoy.wasm.runtime.v8"
    #               vm_id: trace-outbound-filter
    - applyTo: CLUSTER
      match:
        context: SIDECAR_OUTBOUND
      patch:
        operation: ADD
        value: # cluster specification
          name: trace_analyzer
          type: LOGICAL_DNS
          connect_timeout: 0.5s
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: trace_analyzer
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          protocol: TCP
                          address: weblog-svc.weblog.svc.cluster.local
                          port_value: 8000
    # - applyTo: CLUSTER
    #   match:
    #     context: SIDECAR_OUTBOUND
    #   patch:
    #     operation: ADD
    #     value: # cluster specification
    #       name: trace-sampling-manager
    #       type: LOGICAL_DNS
    #       connect_timeout: 0.5s
    #       lb_policy: ROUND_ROBIN
    #       load_assignment:
    #         cluster_name: trace-sampling-manager
    #         endpoints:
    #           - lb_endpoints:
    #               - endpoint:
    #                   address:
    #                     socket_address:
    #                       protocol: TCP
    #                       address: {{WASM_FILTER_TRACE_BACKEND_ADDRESS}}
    #                       port_value: {{WASM_FILTER_TRACE_SAMPLING_PORT}}
